# Đặt tên hiển thị cho bàn phím (tránh lỗi hiện chữ N/A khiến OS tưởng rác và ẩn đi)
CONFIG_ZMK_KEYBOARD_NAME="Aug1st23"

# Tắt chế độ 2Mbps PHY và kéo công suất để máy tính/điện thoại dễ quét thấy hơn
CONFIG_BT_CTLR_PHY_2M=n
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Bật Encoder (Núm xoay)
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Bật Màn hình OLED
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y
CONFIG_ZMK_IDLE_TIMEOUT=15000
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y

# Bật ZMK Studio (Cắm cáp đổi phím qua Web)
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
